### ISSUE TITLE
Coloring the toolbar? 

### ISSUE THREAD

**Issue by Philipp0205** [RaitaroH/LibreOffice-BreezeDark#3]
Really good looking theme!
Everything works fine still in LibreOffice 6.2 except the toolbar-coloring. How did you color your toolbars?

Thank you!

**Comment by RaitaroH** [comment]
You need a desktop dark theme for the toolbars as far as I know. That's how I have them dark.

**Comment by Philipp0205** [comment]
Works. Ty!
